# Generated by Django 4.2.19 on 2025-02-14 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('course_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('video_url', models.URLField(max_length=255)),
                ('video_duration', models.PositiveSmallIntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, related_name='lessons', to='course_catalog.course')),
            ],
        ),
        migrations.CreateModel(
            name='LessonViewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time', models.PositiveSmallIntegerField(default=0)),
                ('last_viewing_time', models.DateTimeField(auto_now=True)),
                (
                    'viewing_status',
                    models.CharField(
                        choices=[('VIEWED', 'Viewed'), ('NOT_VIEWED', 'Not Viewed')],
                        default='NOT_VIEWED',
                        max_length=10,
                    ),
                ),
                (
                    'lesson',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='educational_content.lesson',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
