# Generated by Django 5.2.8 on 2025-11-23 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('video_url', models.URLField(max_length=255)),
                ('video_duration', models.PositiveSmallIntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonViewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time', models.PositiveSmallIntegerField(default=0)),
                ('last_viewing_time', models.DateTimeField(auto_now=True)),
                (
                    'viewing_status',
                    models.CharField(
                        choices=[('viewed', 'Просмотрено'), ('not_viewed', 'Не просмотрено')],
                        default='not_viewed',
                        max_length=10,
                    ),
                ),
                (
                    'lesson',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='lessons.lesson',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инфо просмотров урока',
                'verbose_name_plural': 'Инфо просмотров уроков',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
